# Generated by Django 4.1.7 on 2023-04-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desctiprion', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('time_create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
