# Generated by Django 4.1.7 on 2023-04-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0002_wallet_slug_alter_news_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='slug',
            field=models.CharField(max_length=30),
        ),
    ]
